[project]
name = "privatebin"
version = "0.3.0"
description = "Python library for interacting with PrivateBin's v2 API (PrivateBin >= 1.3) to create, retrieve, and delete encrypted pastes."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{ name = "Ravencentric", email = "me@ravencentric.cc" }]
keywords = ["paste", "pastebin", "privatebin"]
classifiers = [
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: Implementation :: CPython",
  "Typing :: Typed",
]
dependencies = [
  "cryptography>=50",
  "httpx2>=2.10",
  "msgspec>=0.21",
]

[project.urls]
Documentation = "https://ravencentric.cc/privatebin/"
Repository = "https://github.com/Ravencentric/privatebin"

[project.scripts]
privatebin = "privatebin.__main__:main"

[dependency-groups]
dev = [
  { include-group = "docs" },
  { include-group = "check" },
  { include-group = "test" },
]
docs = [
  "mkdocstrings[python]>=1",
  "zensical>=0.0.54",
]
check = [
  "pyrefly>=1.1.1",
  "ruff>=0.16.0",
  "typing-extensions>=4.16",
  { include-group = "types"}
]
test = [
  "coverage[toml]>=7.15",
  "hypothesis>=6.165",
  "pytest>=9.1",
  "pytest-socket>=0.8",
  "tomli>=2.4",
]
types = [
  "httpx>=0.28",
  "niquests>=3.20",
  "requests>=2.34",
  "types-requests>=2.33.0.20260712",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.coverage.report]
exclude_also = [
  "if TYPE_CHECKING:",  # Only used for type-hints
]

[tool.pyrefly]
preset = "all"
python-platform = "all"
project-includes = ["src/**/*.py", "tests/**/*.py"]

[tool.pyrefly.errors]
# 3.10 doesn't have the @override decorator
missing-override-decorator = false
not-required-key-access = false
explicit-any = false
implicit-bool = false
unused-call-result = false

[tool.pytest]
addopts = ["--disable-socket", "--allow-hosts=127.0.0.1", "--showlocals", "-ra"]
filterwarnings = ["error"]
log_cli_level = "INFO"
markers = ["integration: Requires a PrivateBin test instance running on localhost"]
strict = true
testpaths = ["tests"]

[tool.ruff]
line-length = 99

[tool.ruff.lint.extend-per-file-ignores]
"src/privatebin/_cli/*.py" = ["BLE001"]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
