name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "docs/**"
      - ".github/workflows/docs.yml"
      - "zensical.toml"
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions: {}

jobs:
  docs:
    name: Docs
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      - run: uv run zensical build --strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: "./site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
