name: Lint, Format, and Type Check

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/lint-and-type-check.yml"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/lint-and-type-check.yml"
  workflow_dispatch:
  workflow_call:

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: "3.14"
          enable-cache: false

      - name: Install the project
        run: uv sync --all-extras

      - name: Run pyrefly
        run: uv run pyrefly check

      - name: Run ruff lint
        run: uv run ruff check .

      - name: Run ruff format
        run: uv run ruff format --check .
