name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint-and-type-check.yml
  release:
    needs: [tests, lint]
    name: Release
    environment:
      name: pypi
      url: https://pypi.org/project/privatebin/
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Important for changelog

      - name: Install uv
        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
        with:
          python-version: "3.13"

      - name: Build
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4

      - name: Generate a changelog
        run: >-
          uvx git-cliff --config github 
          --github-repo ${{ github.repository }}
          --github-token ${{ github.token }}
          --latest --strip all --output "CHANGELOG.md"

      - name: Create Release
        run: gh release create ${{ github.ref_name }} -F "CHANGELOG.md" --fail-on-no-commits
        env:
          GH_TOKEN: ${{ github.token }}
