name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  FORCE_COLOR: 1
  UV_LOCKED: 1

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
  lint:
    name: Lint
    uses: ./.github/workflows/lint-and-type-check.yml
  release:
    needs: [tests, lint]
    name: Release
    environment:
      name: pypi
      url: https://pypi.org/project/privatebin/
    permissions:
      id-token: write # to publish to PyPI
      contents: write # to publish to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Important for changelog
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: "3.13"
          enable-cache: false

      - name: Build
        run: uv build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0

      - name: Generate a changelog
        run: >-
          uvx git-cliff --config github 
          --github-repo ${GITHUB_REPOSITORY}
          --github-token ${GH_TOKEN}
          --latest --strip all --output "CHANGELOG.md"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create Release
        run: gh release create ${GITHUB_REF_NAME} -F "CHANGELOG.md" --fail-on-no-commits
        env:
          GH_TOKEN: ${{ github.token }}
